/* Ngân hàng câu đã sai theo KC/chủ đề — port từ prototype. */
// ===================================================================
// Ngân hàng câu ĐÃ SAI (MCQ đầy đủ) theo KC + theo chủ đề (fallback)
// Mỗi câu: { level, q, choices{A..D}, answer, expl }
// Dùng cho Tầng 3 (xem lại câu sai) VÀ cho "Luyện với AI".
// ===================================================================

// Câu sai chi tiết cho các KC trọng tâm (học sinh hay yếu)
export const KC_WRONG = {
  gioi_han_ham_so: [
    { level: 'TH', q: 'Tính giới hạn $\\displaystyle\\lim_{x \\to 2} \\dfrac{x^2 - 4}{x - 2}$.',
      choices: { A: '$0$', B: '$2$', C: '$4$', D: '$+\\infty$' }, answer: 'C',
      expl: 'Phân tích $x^2 - 4 = (x-2)(x+2)$, rút gọn còn $x + 2$, thay $x = 2$ được $4$.' },
    { level: 'VD', q: 'Tính $\\displaystyle\\lim_{x \\to 0} \\dfrac{\\sin 3x}{2x}$.',
      choices: { A: '$\\dfrac{3}{2}$', B: '$\\dfrac{2}{3}$', C: '$1$', D: '$3$' }, answer: 'A',
      expl: '$\\frac{\\sin 3x}{2x} = \\frac{3}{2}\\cdot\\frac{\\sin 3x}{3x} \\to \\frac{3}{2}$ vì $\\frac{\\sin u}{u}\\to 1$.' },
    { level: 'VD', q: 'Tính $\\displaystyle\\lim_{x \\to 0} \\dfrac{1 - \\cos x}{x^2}$.',
      choices: { A: '$0$', B: '$\\dfrac{1}{2}$', C: '$1$', D: '$2$' }, answer: 'B',
      expl: 'Dùng $1 - \\cos x = 2\\sin^2\\frac{x}{2}$ hoặc Taylor $\\cos x \\approx 1 - \\frac{x^2}{2}$, được $\\frac{1}{2}$.' },
    { level: 'VDC', q: 'Tính $\\displaystyle\\lim_{x \\to 0} \\dfrac{\\tan x - \\sin x}{x^3}$.',
      choices: { A: '$0$', B: '$\\dfrac{1}{6}$', C: '$\\dfrac{1}{2}$', D: '$1$' }, answer: 'C',
      expl: '$\\tan x - \\sin x = \\sin x\\cdot\\frac{1-\\cos x}{\\cos x} \\sim x\\cdot\\frac{x^2/2}{1} = \\frac{x^3}{2}$, chia $x^3$ ra $\\frac{1}{2}$.' },
  ],
  pt_bpt_mu_logarit: [
    { level: 'TH', q: 'Nghiệm của phương trình $2^{x} = 8$ là:',
      choices: { A: '$x = 2$', B: '$x = 3$', C: '$x = 4$', D: '$x = 6$' }, answer: 'B',
      expl: '$8 = 2^3$ nên $2^x = 2^3 \\Rightarrow x = 3$.' },
    { level: 'VD', q: 'Giải $\\log_2(x - 1) = 3$.',
      choices: { A: '$x = 7$', B: '$x = 8$', C: '$x = 9$', D: '$x = 4$' }, answer: 'C',
      expl: '$\\log_2(x-1) = 3 \\Rightarrow x - 1 = 2^3 = 8 \\Rightarrow x = 9$ (thỏa $x > 1$).' },
    { level: 'VD', q: 'Phương trình $3^{2x} - 4\\cdot 3^{x} + 3 = 0$ có tập nghiệm:',
      choices: { A: '$\\{0; 1\\}$', B: '$\\{1; 3\\}$', C: '$\\{0; 3\\}$', D: '$\\{1\\}$' }, answer: 'A',
      expl: 'Đặt $t = 3^x > 0$: $t^2 - 4t + 3 = 0 \\Rightarrow t = 1$ hoặc $t = 3 \\Rightarrow x = 0$ hoặc $x = 1$.' },
    { level: 'VDC', q: 'Giải $\\log_2 x + \\log_2(x - 2) = 3$.',
      choices: { A: '$x = 2$', B: '$x = 4$', C: '$x = -2; 4$', D: '$x = 8$' }, answer: 'B',
      expl: '$\\log_2[x(x-2)] = 3 \\Rightarrow x^2 - 2x - 8 = 0 \\Rightarrow x = 4$ (loại $x = -2$ vì cần $x > 2$).' },
  ],
  xac_suat_co_dieu_kien: [
    { level: 'TH', q: 'Cho $P(A) = 0,5$; $P(A \\cap B) = 0,2$. Tính $P(B \\mid A)$.',
      choices: { A: '$0,2$', B: '$0,4$', C: '$0,5$', D: '$0,7$' }, answer: 'B',
      expl: '$P(B\\mid A) = \\dfrac{P(A\\cap B)}{P(A)} = \\dfrac{0,2}{0,5} = 0,4$.' },
    { level: 'VD', q: 'Hộp có 4 bi đỏ, 6 bi xanh. Lấy lần lượt 2 bi không hoàn lại. Xác suất bi thứ hai đỏ biết bi thứ nhất đỏ là:',
      choices: { A: '$\\dfrac{4}{10}$', B: '$\\dfrac{3}{9}$', C: '$\\dfrac{4}{9}$', D: '$\\dfrac{1}{3}$' }, answer: 'B',
      expl: 'Sau khi lấy 1 bi đỏ, còn 3 đỏ trên tổng 9 bi: $P = \\frac{3}{9} = \\frac{1}{3}$.' },
    { level: 'VDC', q: 'Nhà máy có 2 dây chuyền: I làm 60% sản phẩm với 2% lỗi, II làm 40% với 5% lỗi. Một sản phẩm lỗi, xác suất nó từ dây chuyền II là:',
      choices: { A: '$\\dfrac{5}{8}$', B: '$\\dfrac{2}{8}$', C: '$\\dfrac{20}{32}$', D: '$\\dfrac{10}{16}$' }, answer: 'A',
      expl: 'Bayes: $P = \\dfrac{0,4\\cdot 0,05}{0,6\\cdot 0,02 + 0,4\\cdot 0,05} = \\dfrac{0,02}{0,032} = \\dfrac{5}{8}$.' },
  ],
  the_tich_khoi: [
    { level: 'TH', q: 'Khối chóp có diện tích đáy $S = 6$ và chiều cao $h = 5$. Thể tích bằng:',
      choices: { A: '$30$', B: '$15$', C: '$10$', D: '$90$' }, answer: 'C',
      expl: '$V = \\frac{1}{3}Sh = \\frac{1}{3}\\cdot 6\\cdot 5 = 10$.' },
    { level: 'VD', q: 'Khối lăng trụ đứng đáy là tam giác vuông cạnh góc vuông $3, 4$, chiều cao $10$. Thể tích là:',
      choices: { A: '$60$', B: '$120$', C: '$30$', D: '$40$' }, answer: 'A',
      expl: 'Diện tích đáy $= \\frac{1}{2}\\cdot 3\\cdot 4 = 6$. $V = S\\cdot h = 6\\cdot 10 = 60$.' },
    { level: 'VDC', q: 'Chóp $S.ABCD$ đáy vuông cạnh $a$, $SA \\perp$ đáy, $SA = a\\sqrt{3}$. Thể tích khối chóp là:',
      choices: { A: '$\\dfrac{a^3\\sqrt{3}}{3}$', B: '$a^3\\sqrt{3}$', C: '$\\dfrac{a^3\\sqrt{3}}{6}$', D: '$\\dfrac{a^3}{3}$' }, answer: 'A',
      expl: '$V = \\frac{1}{3}\\cdot a^2\\cdot a\\sqrt{3} = \\frac{a^3\\sqrt{3}}{3}$.' },
  ],
  cuc_tri: [
    { level: 'TH', q: 'Hàm số $y = x^3 - 3x + 2$ có bao nhiêu điểm cực trị?',
      choices: { A: '$0$', B: '$1$', C: '$2$', D: '$3$' }, answer: 'C',
      expl: "$y' = 3x^2 - 3 = 0 \\Rightarrow x = \\pm 1$ — hai nghiệm đơn nên có 2 cực trị." },
    { level: 'VD', q: 'Hàm số $y = x^4 - 2x^2 + 1$ đạt cực đại tại:',
      choices: { A: '$x = 0$', B: '$x = 1$', C: '$x = -1$', D: '$x = \\pm 1$' }, answer: 'A',
      expl: "$y' = 4x^3 - 4x = 0 \\Rightarrow x = 0, \\pm 1$. Tại $x = 0$ đạo hàm đổi dấu $+ \\to -$ nên cực đại." },
    { level: 'VDC', q: 'Tìm $m$ để $y = x^3 - 3mx^2 + 3(m^2-1)x$ đạt cực đại tại $x = 1$.',
      choices: { A: '$m = 0$', B: '$m = 2$', C: '$m = 0$ hoặc $m = 2$', D: '$m = 1$' }, answer: 'B',
      expl: "$y' = 3x^2 - 6mx + 3(m^2-1)$. $y'(1) = 0$ và $y''(1) < 0$ cho $m = 2$." },
  ],
  hoan_vi_chinh_hop_to_hop: [
    { level: 'TH', q: 'Số cách chọn 2 học sinh từ 5 học sinh là:',
      choices: { A: '$10$', B: '$20$', C: '$25$', D: '$120$' }, answer: 'A',
      expl: 'Chọn không kể thứ tự: $C_5^2 = \\dfrac{5!}{2!\\,3!} = 10$.' },
    { level: 'VD', q: 'Có bao nhiêu số tự nhiên có 3 chữ số khác nhau lập từ $\\{1,2,3,4,5\\}$?',
      choices: { A: '$60$', B: '$125$', C: '$10$', D: '$120$' }, answer: 'A',
      expl: 'Có thứ tự, không lặp: $A_5^3 = 5\\cdot 4\\cdot 3 = 60$.' },
    { level: 'VDC', q: 'Một tổ 10 người chọn 3 người vào ban (trưởng, phó, thư kí). Số cách là:',
      choices: { A: '$120$', B: '$720$', C: '$1000$', D: '$30$' }, answer: 'B',
      expl: 'Ba vai trò khác nhau (có thứ tự): $A_{10}^3 = 10\\cdot 9\\cdot 8 = 720$.' },
  ],
  pt_luong_giac: [
    { level: 'TH', q: 'Nghiệm của $\\sin x = \\dfrac{1}{2}$ là:',
      choices: { A: '$x = \\dfrac{\\pi}{6} + k2\\pi$', B: '$x = \\dfrac{\\pi}{6} + k2\\pi$ hoặc $x = \\dfrac{5\\pi}{6} + k2\\pi$', C: '$x = \\dfrac{\\pi}{3} + k2\\pi$', D: '$x = \\dfrac{\\pi}{6} + k\\pi$' }, answer: 'B',
      expl: '$\\sin x = \\frac{1}{2} \\Rightarrow x = \\frac{\\pi}{6} + k2\\pi$ hoặc $x = \\pi - \\frac{\\pi}{6} + k2\\pi = \\frac{5\\pi}{6} + k2\\pi$.' },
    { level: 'VD', q: 'Phương trình $2\\cos^2 x - 3\\cos x + 1 = 0$ có nghiệm:',
      choices: { A: '$x = k2\\pi$ hoặc $x = \\pm\\dfrac{\\pi}{3} + k2\\pi$', B: '$x = \\dfrac{\\pi}{2} + k\\pi$', C: '$x = k\\pi$', D: '$x = \\pm\\dfrac{\\pi}{6} + k2\\pi$' }, answer: 'A',
      expl: 'Đặt $t = \\cos x$: $2t^2 - 3t + 1 = 0 \\Rightarrow t = 1$ hoặc $t = \\frac{1}{2}$, suy ra nghiệm tương ứng.' },
    { level: 'VDC', q: 'Số nghiệm của $\\sin 2x = \\cos x$ trên $[0; 2\\pi]$ là:',
      choices: { A: '$2$', B: '$3$', C: '$4$', D: '$5$' }, answer: 'C',
      expl: '$\\sin 2x = \\cos x \\Rightarrow \\cos x(2\\sin x - 1) = 0$, được $x = \\frac{\\pi}{2}, \\frac{3\\pi}{2}, \\frac{\\pi}{6}, \\frac{5\\pi}{6}$ — 4 nghiệm.' },
  ],
  tich_phan: [
    { level: 'TH', q: 'Tính $\\displaystyle\\int_0^2 x\\,dx$.',
      choices: { A: '$1$', B: '$2$', C: '$4$', D: '$\\dfrac{1}{2}$' }, answer: 'B',
      expl: '$\\int_0^2 x\\,dx = \\frac{x^2}{2}\\Big|_0^2 = \\frac{4}{2} = 2$.' },
    { level: 'VD', q: 'Tính $\\displaystyle\\int_0^1 (3x^2 + 2x)\\,dx$.',
      choices: { A: '$2$', B: '$3$', C: '$1$', D: '$\\dfrac{5}{2}$' }, answer: 'A',
      expl: '$= (x^3 + x^2)\\Big|_0^1 = 1 + 1 = 2$.' },
    { level: 'VDC', q: 'Tính $\\displaystyle\\int_0^{\\pi/2} \\sin x\\cos x\\,dx$.',
      choices: { A: '$\\dfrac{1}{2}$', B: '$1$', C: '$\\dfrac{1}{4}$', D: '$0$' }, answer: 'A',
      expl: '$\\sin x\\cos x = \\frac{1}{2}\\sin 2x$. $\\int_0^{\\pi/2}\\frac{1}{2}\\sin 2x\\,dx = \\frac{1}{2}$.' },
  ],
  gtln_gtnn: [
    { level: 'VD', q: 'GTLN của $y = -x^2 + 4x - 1$ trên $\\mathbb{R}$ là:',
      choices: { A: '$3$', B: '$4$', C: '$-1$', D: '$2$' }, answer: 'A',
      expl: "$y' = -2x + 4 = 0 \\Rightarrow x = 2$, $y(2) = 3$ là GTLN." },
    { level: 'VD', q: 'GTNN của $y = x + \\dfrac{4}{x}$ với $x > 0$ là:',
      choices: { A: '$2$', B: '$4$', C: '$8$', D: '$1$' }, answer: 'B',
      expl: 'Cauchy: $x + \\frac{4}{x} \\ge 2\\sqrt{4} = 4$, dấu bằng khi $x = 2$.' },
    { level: 'VDC', q: 'GTLN của $y = x\\sqrt{4 - x^2}$ là:',
      choices: { A: '$2$', B: '$4$', C: '$\\sqrt{2}$', D: '$1$' }, answer: 'A',
      expl: 'Đặt miền $[-2;2]$, $y\' = \\frac{4 - 2x^2}{\\sqrt{4-x^2}} = 0 \\Rightarrow x = \\sqrt{2}$, $y = 2$.' },
  ],
  quan_he_vuong_goc: [
    { level: 'TH', q: 'Cho hình chóp $S.ABC$ có $SA \\perp (ABC)$. Khẳng định nào đúng?',
      choices: { A: '$SA \\perp BC$', B: '$SA \\perp SB$', C: '$BC \\perp (SAB)$', D: '$AB \\perp BC$' }, answer: 'A',
      expl: 'Vì $SA \\perp (ABC)$ nên $SA$ vuông góc với mọi đường thẳng nằm trong mặt phẳng đáy, trong đó có $BC$.' },
    { level: 'VD', q: 'Để $BC \\perp (SAB)$ trong chóp có $SA \\perp (ABC)$, cần thêm điều kiện:',
      choices: { A: '$BC \\perp AB$', B: '$BC \\perp SB$', C: '$AB \\perp SB$', D: '$SA = AB$' }, answer: 'A',
      expl: '$BC \\perp SA$ (sẵn có) và nếu $BC \\perp AB$ thì $BC \\perp (SAB)$ theo dấu hiệu hai đường cắt nhau.' },
  ],
};

// Fallback theo CHỦ ĐỀ — dùng khi KC chưa có ngân hàng riêng (vẫn đúng mạch nội dung)
export const TOPIC_WRONG = {
  menh_de_tap_hop: [
    { level: 'TH', q: 'Cho $A = \\{1;2;3;4\\}$, $B = \\{3;4;5;6\\}$. Tập $A \\cap B$ là:',
      choices: { A: '$\\{3;4\\}$', B: '$\\{1;2\\}$', C: '$\\{5;6\\}$', D: '$\\{1;2;3;4;5;6\\}$' }, answer: 'A',
      expl: 'Giao là các phần tử thuộc cả hai tập: $\\{3; 4\\}$.' },
    { level: 'NB', q: 'Mệnh đề phủ định của "$\\forall x \\in \\mathbb{R}, x^2 \\ge 0$" là:',
      choices: { A: '$\\exists x \\in \\mathbb{R}, x^2 < 0$', B: '$\\forall x, x^2 \\le 0$', C: '$\\exists x, x^2 > 0$', D: '$\\forall x, x^2 < 0$' }, answer: 'A',
      expl: 'Phủ định $\\forall$ thành $\\exists$ và phủ định mệnh đề bên trong: $x^2 < 0$.' },
  ],
  bpt_hai_an: [
    { level: 'VD', q: 'Trên miền nghiệm của hệ $x \\ge 0, y \\ge 0, x + y \\le 4$, GTLN của $F = 3x + 2y$ là:',
      choices: { A: '$12$', B: '$8$', C: '$10$', D: '$6$' }, answer: 'A',
      expl: 'F đạt cực trị tại đỉnh. Tại $(4;0)$: $F = 12$ — lớn nhất.' },
  ],
  ham_so_dai_so: [
    { level: 'TH', q: 'Parabol $y = x^2 - 4x + 3$ có tọa độ đỉnh là:',
      choices: { A: '$(2; -1)$', B: '$(-2; 15)$', C: '$(2; 3)$', D: '$(1; 0)$' }, answer: 'A',
      expl: 'Hoành độ đỉnh $x = -\\frac{b}{2a} = 2$, tung độ $y(2) = -1$.' },
    { level: 'VD', q: 'Tập nghiệm của bất phương trình $x^2 - 5x + 6 < 0$ là:',
      choices: { A: '$(2; 3)$', B: '$(-\\infty;2)\\cup(3;+\\infty)$', C: '$[2;3]$', D: '$(3;+\\infty)$' }, answer: 'A',
      expl: 'Tam thức âm giữa hai nghiệm $2$ và $3$ nên nghiệm là khoảng $(2;3)$.' },
  ],
  to_hop: [
    { level: 'NB', q: 'Số hoán vị của 4 phần tử là:',
      choices: { A: '$24$', B: '$12$', C: '$4$', D: '$16$' }, answer: 'A',
      expl: '$P_4 = 4! = 24$.' },
  ],
  luong_giac: [
    { level: 'TH', q: 'Cho $\\sin\\alpha = \\dfrac{3}{5}$, $\\alpha$ nhọn. Khi đó $\\cos\\alpha$ bằng:',
      choices: { A: '$\\dfrac{4}{5}$', B: '$\\dfrac{3}{4}$', C: '$\\dfrac{5}{4}$', D: '$-\\dfrac{4}{5}$' }, answer: 'A',
      expl: '$\\cos\\alpha = \\sqrt{1 - \\sin^2\\alpha} = \\sqrt{1 - 9/25} = \\frac{4}{5}$ (vì $\\alpha$ nhọn).' },
  ],
  day_so_cap_so: [
    { level: 'TH', q: 'Cấp số cộng có $u_1 = 2$, $d = 3$. Số hạng $u_5$ bằng:',
      choices: { A: '$14$', B: '$17$', C: '$11$', D: '$15$' }, answer: 'A',
      expl: '$u_5 = u_1 + 4d = 2 + 12 = 14$.' },
    { level: 'VD', q: 'Cấp số nhân $u_1 = 3$, $q = 2$. Tổng $S_4$ bằng:',
      choices: { A: '$45$', B: '$48$', C: '$24$', D: '$30$' }, answer: 'A',
      expl: '$S_4 = u_1\\frac{q^4 - 1}{q - 1} = 3\\cdot\\frac{15}{1} = 45$.' },
  ],
  mu_logarit: [
    { level: 'NB', q: 'Giá trị của $\\log_2 16$ là:',
      choices: { A: '$4$', B: '$8$', C: '$2$', D: '$16$' }, answer: 'A',
      expl: '$16 = 2^4$ nên $\\log_2 16 = 4$.' },
  ],
  gioi_han: [
    { level: 'TH', q: 'Tính $\\displaystyle\\lim_{n \\to \\infty} \\dfrac{2n + 1}{n - 3}$.',
      choices: { A: '$2$', B: '$0$', C: '$+\\infty$', D: '$\\dfrac{1}{3}$' }, answer: 'A',
      expl: 'Chia tử mẫu cho $n$: $\\frac{2 + 1/n}{1 - 3/n} \\to 2$.' },
  ],
  dao_ham: [
    { level: 'TH', q: 'Đạo hàm của $y = x^3 - 2x$ là:',
      choices: { A: '$3x^2 - 2$', B: '$x^2 - 2$', C: '$3x^2$', D: '$3x - 2$' }, answer: 'A',
      expl: "$(x^3)' = 3x^2$, $(-2x)' = -2$." },
    { level: 'VD', q: 'PT tiếp tuyến của $y = x^2$ tại điểm $x_0 = 1$ là:',
      choices: { A: '$y = 2x - 1$', B: '$y = 2x + 1$', C: '$y = x - 1$', D: '$y = 2x$' }, answer: 'A',
      expl: "$y'(1) = 2$, $y(1) = 1$. Tiếp tuyến: $y = 2(x - 1) + 1 = 2x - 1$." },
  ],
  khao_sat_ham_so: [
    { level: 'TH', q: 'Hàm số $y = x^3 - 3x$ nghịch biến trên khoảng:',
      choices: { A: '$(-1; 1)$', B: '$(-\\infty; -1)$', C: '$(1; +\\infty)$', D: '$(0; 2)$' }, answer: 'A',
      expl: "$y' = 3x^2 - 3 < 0 \\Leftrightarrow -1 < x < 1$." },
  ],
  tich_phan: [
    { level: 'TH', q: 'Nguyên hàm của $f(x) = 2x$ là:',
      choices: { A: '$x^2 + C$', B: '$2x^2 + C$', C: '$x + C$', D: '$\\dfrac{x^2}{2} + C$' }, answer: 'A',
      expl: '$\\int 2x\\,dx = x^2 + C$.' },
  ],
  hinh_phang_co_so: [
    { level: 'TH', q: 'Tam giác có $a = 7$, $b = 8$, $C = 60°$. Cạnh $c$ bằng:',
      choices: { A: '$\\sqrt{57}$', B: '$\\sqrt{113}$', C: '$7$', D: '$8$' }, answer: 'A',
      expl: 'Định lí côsin: $c^2 = 49 + 64 - 2\\cdot 7\\cdot 8\\cdot\\frac{1}{2} = 57$.' },
  ],
  toa_do_phang: [
    { level: 'TH', q: 'Khoảng cách từ $M(1; 2)$ đến đường thẳng $3x + 4y - 1 = 0$ là:',
      choices: { A: '$2$', B: '$1$', C: '$\\dfrac{10}{5}$', D: '$3$' }, answer: 'A',
      expl: '$d = \\frac{|3 + 8 - 1|}{\\sqrt{9 + 16}} = \\frac{10}{5} = 2$.' },
    { level: 'VD', q: 'Đường tròn $(x-1)^2 + (y+2)^2 = 9$ có tâm và bán kính:',
      choices: { A: '$I(1;-2), R = 3$', B: '$I(-1;2), R = 9$', C: '$I(1;-2), R = 9$', D: '$I(-1;2), R = 3$' }, answer: 'A',
      expl: 'Dạng chuẩn cho tâm $I(1;-2)$, bán kính $R = \\sqrt{9} = 3$.' },
  ],
  khong_gian_tong_hop: [
    { level: 'TH', q: 'Hai mặt phẳng phân biệt cùng vuông góc với một đường thẳng thì:',
      choices: { A: 'song song nhau', B: 'cắt nhau', C: 'trùng nhau', D: 'vuông góc nhau' }, answer: 'A',
      expl: 'Cùng vuông góc một đường thẳng và phân biệt nên hai mặt phẳng song song.' },
  ],
  toa_do_khong_gian: [
    { level: 'TH', q: 'Mặt cầu $x^2 + y^2 + z^2 - 2x - 4y = 0$ có bán kính:',
      choices: { A: '$\\sqrt{5}$', B: '$5$', C: '$\\sqrt{3}$', D: '$2$' }, answer: 'A',
      expl: 'Tâm $(1;2;0)$, $R = \\sqrt{1 + 4 + 0 - 0} = \\sqrt{5}$.' },
    { level: 'VD', q: 'Khoảng cách từ $O$ đến mặt phẳng $2x - y + 2z - 6 = 0$ là:',
      choices: { A: '$2$', B: '$3$', C: '$6$', D: '$1$' }, answer: 'A',
      expl: '$d = \\frac{|-6|}{\\sqrt{4 + 1 + 4}} = \\frac{6}{3} = 2$.' },
  ],
  thong_ke: [
    { level: 'TH', q: 'Số trung bình của mẫu $\\{2; 4; 4; 6; 9\\}$ là:',
      choices: { A: '$5$', B: '$4$', C: '$4,5$', D: '$6$' }, answer: 'A',
      expl: '$\\bar{x} = \\frac{2+4+4+6+9}{5} = \\frac{25}{5} = 5$.' },
  ],
  xac_suat: [
    { level: 'TH', q: 'Gieo một con xúc xắc cân đối. Xác suất ra mặt chẵn là:',
      choices: { A: '$\\dfrac{1}{2}$', B: '$\\dfrac{1}{3}$', C: '$\\dfrac{1}{6}$', D: '$\\dfrac{2}{3}$' }, answer: 'A',
      expl: 'Mặt chẵn: $\\{2;4;6\\}$, có 3 trong 6 khả năng: $P = \\frac{1}{2}$.' },
  ],
};
